<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StaffSeeder extends Seeder
{
    public function run()
    {
        $fields = [
            [
                'name' => 'gender',
                'label' => 'Gender',
                'placeholder' => 'Select gender',
                'field_type' => 'select',
                'options' => json_encode(['Male', 'Female', 'Other']),
                'description' => 'Options may include Male, Female, Other.',
                'sort' => 3,
                'category' => 'Personal Information',
                'model_type' => 'Staff',
                'has_options' => true,
            ],
            [
                'name' => 'dob',
                'label' => 'Date of Birth',
                'placeholder' => 'Select date of birth',
                'field_type' => 'date',
                'description' => 'Staff member\'s birthdate.',
                'sort' => 4,
                'category' => 'Personal Information',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'national_id',
                'label' => 'National Identification Number',
                'placeholder' => 'Enter national ID',
                'field_type' => 'text',
                'description' => 'Government-issued ID number.',
                'sort' => 5,
                'category' => 'Personal Information',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'phone_number',
                'label' => 'Phone Number',
                'placeholder' => 'Enter phone number',
                'field_type' => 'text',
                'description' => 'Primary contact number.',
                'sort' => 7,
                'category' => 'Contact Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'address',
                'label' => 'Residential Address',
                'placeholder' => 'Enter residential address',
                'field_type' => 'textarea',
                'description' => 'Current home address.',
                'sort' => 8,
                'category' => 'Contact Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'emergency_contact_name',
                'label' => 'Emergency Contact Name',
                'placeholder' => 'Enter emergency contact name',
                'field_type' => 'text',
                'description' => 'Name of the emergency contact person.',
                'sort' => 9,
                'category' => 'Contact Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'emergency_contact_phone',
                'label' => 'Emergency Contact Phone',
                'placeholder' => 'Enter emergency contact phone',
                'field_type' => 'text',
                'description' => 'Phone number of the emergency contact.',
                'sort' => 10,
                'category' => 'Contact Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'employee_id',
                'label' => 'Employee ID',
                'placeholder' => 'Enter employee ID',
                'field_type' => 'text',
                'description' => 'Unique identifier for the staff member within the institution.',
                'sort' => 11,
                'category' => 'Employment Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'date_of_hire',
                'label' => 'Date of Hire',
                'placeholder' => 'Select date of hire',
                'field_type' => 'date',
                'description' => 'When the staff member commenced employment.',
                'sort' => 12,
                'category' => 'Employment Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'job_title',
                'label' => 'Job Title',
                'placeholder' => 'Enter job title',
                'field_type' => 'text',
                'description' => 'Official designation, e.g., Mathematics Teacher, Administrator.',
                'sort' => 13,
                'category' => 'Employment Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'department',
                'label' => 'Department',
                'placeholder' => 'Enter department',
                'field_type' => 'text',
                'description' => 'Department or faculty the staff belongs to.',
                'sort' => 14,
                'category' => 'Employment Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'employment_type',
                'label' => 'Employment Type',
                'placeholder' => 'Select employment type',
                'field_type' => 'select',
                'options' => json_encode(['Full-time', 'Part-time', 'Contractual']),
                'description' => 'Type of employment.',
                'sort' => 15,
                'category' => 'Employment Details',
                'model_type' => 'Staff',
                'has_options' => true,
            ],
            [
                'name' => 'salary',
                'label' => 'Salary',
                'placeholder' => 'Enter salary',
                'field_type' => 'number',
                'description' => 'Compensation details.',
                'sort' => 16,
                'category' => 'Employment Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'highest_degree',
                'label' => 'Highest Degree Earned',
                'placeholder' => 'Enter highest degree',
                'field_type' => 'text',
                'description' => 'e.g., Bachelor of Science in Education.',
                'sort' => 17,
                'category' => 'Qualifications',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'field_of_study',
                'label' => 'Field of Study',
                'placeholder' => 'Enter field of study',
                'field_type' => 'text',
                'description' => 'Major or specialization.',
                'sort' => 18,
                'category' => 'Qualifications',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'institution',
                'label' => 'Institution',
                'placeholder' => 'Enter institution name',
                'field_type' => 'text',
                'description' => 'Name of the university or college attended.',
                'sort' => 19,
                'category' => 'Qualifications',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'graduation_year',
                'label' => 'Year of Graduation',
                'placeholder' => 'Enter graduation year',
                'field_type' => 'number',
                'description' => 'Completion year of the highest degree.',
                'sort' => 20,
                'category' => 'Qualifications',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'certifications',
                'label' => 'Certifications',
                'placeholder' => 'Enter certifications',
                'field_type' => 'text',
                'description' => 'Additional relevant certifications.',
                'sort' => 21,
                'category' => 'Qualifications',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'previous_employer',
                'label' => 'Previous Employer',
                'placeholder' => 'Enter previous employer',
                'field_type' => 'text',
                'description' => 'Last place of employment.',
                'sort' => 22,
                'category' => 'Work Experience',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'years_of_experience',
                'label' => 'Years of Experience',
                'placeholder' => 'Enter years of experience',
                'field_type' => 'number',
                'description' => 'Total years in the profession.',
                'sort' => 23,
                'category' => 'Work Experience',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'skills',
                'label' => 'Skills',
                'placeholder' => 'Enter relevant skills',
                'field_type' => 'text',
                'description' => 'Relevant skills and competencies.',
                'sort' => 24,
                'category' => 'Work Experience',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'blood_type',
                'label' => 'Blood Type',
                'placeholder' => 'Enter blood type',
                'field_type' => 'text',
                'description' => 'e.g., O+, A-.',
                'sort' => 25,
                'category' => 'Medical Information',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'allergies',
                'label' => 'Allergies',
                'placeholder' => 'Enter known allergies',
                'field_type' => 'text',
                'description' => 'Known allergies, if any.',
                'sort' => 26,
                'category' => 'Medical Information',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'medical_conditions',
                'label' => 'Medical Conditions',
                'placeholder' => 'Enter medical conditions',
                'field_type' => 'text',
                'description' => 'Chronic illnesses or conditions.',
                'sort' => 27,
                'category' => 'Medical Information',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'bank_name',
                'label' => 'Bank Name',
                'placeholder' => 'Enter bank name',
                'field_type' => 'text',
                'description' => 'Name of the bank for salary deposits.',
                'sort' => 28,
                'category' => 'Banking Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'account_number',
                'label' => 'Account Number',
                'placeholder' => 'Enter account number',
                'field_type' => 'text',
                'description' => 'Staff\'s bank account number.',
                'sort' => 29,
                'category' => 'Banking Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'branch',
                'label' => 'Branch',
                'placeholder' => 'Enter bank branch details',
                'field_type' => 'text',
                'description' => 'Bank branch details.',
                'sort' => 30,
                'category' => 'Banking Details',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'marital_status',
                'label' => 'Marital Status',
                'placeholder' => 'Select marital status',
                'field_type' => 'select',
                'options' => json_encode(['Single', 'Married', 'Divorced']),
                'description' => 'Marital status of the staff member.',
                'sort' => 31,
                'category' => 'Additional Information',
                'model_type' => 'Staff',
                'has_options' => true,
            ],
            [
                'name' => 'spouse_name',
                'label' => 'Spouse Name',
                'placeholder' => 'Enter spouse name',
                'field_type' => 'text',
                'description' => 'If applicable, name of the spouse.',
                'sort' => 32,
                'category' => 'Additional Information',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'dependents',
                'label' => 'Number of Dependents',
                'placeholder' => 'Enter number of dependents',
                'field_type' => 'number',
                'description' => 'Count of dependents.',
                'sort' => 33,
                'category' => 'Additional Information',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'hobbies',
                'label' => 'Hobbies/Interests',
                'placeholder' => 'Enter hobbies or interests',
                'field_type' => 'text',
                'description' => 'Personal interests of the staff member.',
                'sort' => 34,
                'category' => 'Additional Information',
                'model_type' => 'Staff',
            ],
            [
                'name' => 'languages',
                'label' => 'Languages Spoken',
                'placeholder' => 'Enter languages spoken',
                'field_type' => 'text',
                'description' => 'Languages the staff is proficient in.',
                'sort' => 35,
                'category' => 'Additional Information',
                'model_type' => 'Staff',
            ],
        ];

        foreach ($fields as $field) {
            DB::table('custom_fields')->insert($field);
        }
    }
}
