<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * SubjectResource – JSON transformation layer for the Subject model.
 *
 * Purpose & Problems Solved:
 * ─────────────────────────────────────────────────────────────────────────
 * • Single source of truth for the JSON shape of a Subject sent to the
 *   frontend — no ad-hoc toArray() calls scattered across controllers.
 * • Hides internal/sensitive columns (school_id, pivot internals, raw
 *   deleted_at timestamp) while exposing clean, typed, frontend-ready fields.
 * • Resolves dynamic enum labels (type_label, category_label) so the
 *   frontend never has to look them up independently.
 * • Exposes computed flags (is_active, is_trashed, is_elective, is_global)
 *   as explicit booleans — no ternary logic needed in Vue templates.
 * • Provides formatted date strings alongside raw ISO strings so components
 *   can choose between human-readable display and date-picker binding.
 * • Conditionally includes the schoolSections relation only when it has
 *   already been eager-loaded — prevents N+1 queries if the relation was
 *   intentionally omitted.
 * • Works for both single-resource responses (show, store, update) and
 *   collection responses (index DataTable) via SubjectResource::collection().
 *
 * Fits into the Subjects module:
 * ─────────────────────────────────────────────────────────────────────────
 * • Consumed by SubjectController (all actions).
 * • Shape matches the SubjectListItem / Subject TypeScript interfaces in
 *   resources/js/types/subject.ts so the frontend stays fully type-safe.
 * • school_section_names (comma-joined) mirrors the extra DataTable column
 *   generated by HasTableQuery so table rows and modal pre-fill are consistent.
 */
class SubjectResource extends JsonResource
{
    /**
     * Transform the Subject model into an array.
     *
     * Conditional fields:
     *  • school_sections  – only when the relation is loaded (whenLoaded guard)
     *  • deleted_at_raw   – only when the record is soft-deleted
     *  • type_label / category_label – resolved from DynamicEnum accessors on
     *    the model; fall back to the raw value if the enum is not seeded yet
     */
    public function toArray(Request $request): array
    {
        return [
            // ── Identity ──────────────────────────────────────────────────
            'id' => $this->id,
            'name' => $this->name,
            'code' => $this->code,

            // ── Classification ────────────────────────────────────────────
            'type' => $this->type,
            'type_label' => $this->type_label     // accessor on model
                ?? $this->type,        // fallback: raw value
            'category' => $this->category,
            'category_label' => $this->category_label // accessor on model
                ?? $this->category,

            // ── Academic details ──────────────────────────────────────────
            'credit_hours' => $this->credit_hours,
            'description' => $this->description,

            // ── Flags ─────────────────────────────────────────────────────
            'is_elective' => (bool) $this->is_elective,
            'is_active' => (bool) $this->is_active,
            'is_trashed' => $this->trashed(),

            // ── Sections (many-to-many) ───────────────────────────────────
            // Only emitted when the relation was explicitly eager-loaded.
            // This prevents silent N+1 queries on list responses where
            // school_section_names (the joined string) is used instead.
            'school_sections' => $this->whenLoaded(
                'schoolSections',
                fn() => $this->schoolSections->map(fn($s) => [
                    'id' => $s->id,
                    'name' => $s->name,
                    'short_code' => $s->short_code ?? null,
                ])
            ),

            // Convenience string for DataTable column display.
            // Populated from the WithCount/schoolSections relation when loaded;
            // falls back to the HasTableQuery virtual column when not.
            'school_section_names' => $this->whenLoaded(
                'schoolSections',
                fn() => $this->schoolSections->pluck('name')->join(', '),
                $this->school_section_names ?? null  // virtual col from tableQuery
            ),

            // ── Timestamps ────────────────────────────────────────────────
            // Human-readable for display; raw ISO for date-pickers / JS Date.
            'created_at' => $this->created_at?->format('d M Y'),
            'created_at_raw' => $this->created_at?->toISOString(),

            'updated_at' => $this->updated_at?->format('d M Y'),
            'updated_at_raw' => $this->updated_at?->toISOString(),

            // Only included when the record is in the trash.
            'deleted_at' => $this->when(
                $this->trashed(),
                fn() => $this->deleted_at?->format('d M Y')
            ),
            'deleted_at_raw' => $this->when(
                $this->trashed(),
                fn() => $this->deleted_at?->toISOString()
            ),
        ];
    }

    /**
     * Customize the outgoing response wrapper.
     *
     * Adds a top-level "success" flag so the frontend can check
     * response.data.success without inspecting the HTTP status code.
     */
    public function withResponse(Request $request, \Illuminate\Http\JsonResponse $response): void
    {
        // Only wrap single-resource responses (not collection wrappers).
        $data = $response->getData(true);

        if (isset($data['data']) && !isset($data['success'])) {
            $response->setData(array_merge(['success' => true], $data));
        }
    }
}
