/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "profile.setting": [],
    "profile.setting.update": [],
    "website.localization": [],
    "website.localization.post": [],
    "website.invoice": [],
    "website.invoice.post": [],
    "website.custom_field": [],
    "website.custom_field.post": [],
    "system.email": [],
    "system.email.post": [],
    "system.email.template": [],
    "system.email.template.post": [],
    "system.sms": [],
    "system.sms.post": [],
    "system.otp": [],
    "system.otp.post": [],
    "system.gdpr": [],
    "system.gdpr.post": [],
    "settings.payment-gate-ways": [],
    "settings.tax": [],
    "settings.fees": [],
    "settings.maintainance": [],
    "settings.storage": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
