<?php

// Permission catalogue part 5 (Phase 2)
return [
    ['name' => 'departments.view', 'display_name' => 'View Departments', 'description' => 'View all departments for a school'],
    ['name' => 'departments.create', 'display_name' => 'Create Departments', 'description' => 'Create new departments for a school'],
    ['name' => 'departments.update', 'display_name' => 'Update Departments', 'description' => 'Update existing departments for a school'],
    ['name' => 'departments.delete', 'display_name' => 'Delete Departments', 'description' => 'Delete departments for a school'],
    ['name' => 'departments.restore', 'display_name' => 'Restore Departments', 'description' => 'Restore deleted departments for a school'],
    ['name' => 'departments.force-delete', 'display_name' => 'Force Delete Departments', 'description' => 'Permanently delete departments for a school'],
    ['name' => 'departments.assign-role', 'display_name' => 'Assign Roles to Departments', 'description' => 'Assign roles to departments'],
    ['name' => 'departments.view-users', 'display_name' => 'View Users in Departments', 'description' => 'View users in departments'],
    ['name' => 'notices.view', 'display_name' => 'View Notices', 'description' => 'View all notices for a school'],
    ['name' => 'notices.create', 'display_name' => 'Create Notices', 'description' => 'Create new notices for a school'],
    ['name' => 'notices.update', 'display_name' => 'Update Notices', 'description' => 'Update existing notices for a school'],
    ['name' => 'notices.delete', 'display_name' => 'Delete Notices', 'description' => 'Delete notices for a school'],
    ['name' => 'notices.restore', 'display_name' => 'Restore Notices', 'description' => 'Restore deleted notices for a school'],
    ['name' => 'notices.force-delete', 'display_name' => 'Force Delete Notices', 'description' => 'Permanently delete notices for a school'],
    ['name' => 'notices.mark-read', 'display_name' => 'Mark Notices as Read', 'description' => 'Mark notices as read for a user'],
    ['name' => 'routes.view', 'display_name' => 'View Routes', 'description' => 'View all routes for a school'],
    ['name' => 'routes.create', 'display_name' => 'Create Routes', 'description' => 'Create new routes for a school'],
    ['name' => 'routes.update', 'display_name' => 'Update Routes', 'description' => 'Update existing routes for a school'],
    ['name' => 'routes.delete', 'display_name' => 'Delete Routes', 'description' => 'Delete routes for a school'],
    ['name' => 'routes.restore', 'display_name' => 'Restore Routes', 'description' => 'Restore deleted routes for a school'],
    ['name' => 'routes.force-delete', 'display_name' => 'Force Delete Routes', 'description' => 'Permanently delete routes for a school'],
    ['name' => 'vehicles.view', 'display_name' => 'View Vehicles', 'description' => 'View all vehicles for a school'],
    ['name' => 'vehicles.create', 'display_name' => 'Create Vehicles', 'description' => 'Create new vehicles for a school'],
    ['name' => 'vehicles.update', 'display_name' => 'Update Vehicles', 'description' => 'Update existing vehicles for a school'],
    ['name' => 'vehicles.delete', 'display_name' => 'Delete Vehicles', 'description' => 'Delete vehicles for a school'],
    ['name' => 'vehicles.restore', 'display_name' => 'Restore Vehicles', 'description' => 'Restore deleted vehicles for a school'],
    ['name' => 'vehicles.force-delete', 'display_name' => 'Force Delete Vehicles', 'description' => 'Permanently delete vehicles for a school'],
    ['name' => 'vehicles.assign-driver', 'display_name' => 'Assign Driver', 'description' => 'Assign a driver to a vehicle'],
    ['name' => 'vehicle-documents.view', 'display_name' => 'View Vehicle Documents', 'description' => 'View all vehicle documents for a school'],
    ['name' => 'vehicle-documents.create', 'display_name' => 'Create Vehicle Documents', 'description' => 'Create new vehicle documents for a school'],
    ['name' => 'vehicle-documents.update', 'display_name' => 'Update Vehicle Documents', 'description' => 'Update existing vehicle documents for a school'],
    ['name' => 'vehicle-documents.delete', 'display_name' => 'Delete Vehicle Documents', 'description' => 'Delete vehicle documents for a school'],
    ['name' => 'vehicle-documents.restore', 'display_name' => 'Restore Vehicle Documents', 'description' => 'Restore deleted vehicle documents for a school'],
];
