<?php

// Permission catalogue part 6 (Phase 2)
return [
    ['name' => 'vehicle-documents.force-delete', 'display_name' => 'Force Delete Vehicle Documents', 'description' => 'Permanently delete vehicle documents for a school'],
    ['name' => 'vehicle-expenses.view', 'display_name' => 'View Vehicle Expenses', 'description' => 'View all vehicle expenses for a school'],
    ['name' => 'vehicle-expenses.create', 'display_name' => 'Create Vehicle Expenses', 'description' => 'Create new vehicle expenses for a school'],
    ['name' => 'vehicle-expenses.update', 'display_name' => 'Update Vehicle Expenses', 'description' => 'Update existing vehicle expenses for a school'],
    ['name' => 'vehicle-expenses.delete', 'display_name' => 'Delete Vehicle Expenses', 'description' => 'Delete vehicle expenses for a school'],
    ['name' => 'vehicle-expenses.restore', 'display_name' => 'Restore Vehicle Expenses', 'description' => 'Restore deleted vehicle expenses for a school'],
    ['name' => 'vehicle-expenses.force-delete', 'display_name' => 'Force Delete Vehicle Expenses', 'description' => 'Permanently delete vehicle expenses for a school'],
    ['name' => 'hostel.view-any', 'display_name' => 'View All Hostels', 'description' => 'Allows the user to view all hostels for a school.'],
    ['name' => 'hostel.view', 'display_name' => 'View Hostel', 'description' => 'Allows the user to view a specific hostel for a school.'],
    ['name' => 'hostel.create', 'display_name' => 'Create Hostels', 'description' => 'Allows the user to create new hostels for a school.'],
    ['name' => 'hostel.update', 'display_name' => 'Update Hostels', 'description' => 'Allows the user to update existing hostels for a school.'],
    ['name' => 'hostel.delete', 'display_name' => 'Delete Hostels', 'description' => 'Allows the user to delete hostels for a school.'],
    ['name' => 'hostel.restore', 'display_name' => 'Restore Hostels', 'description' => 'Allows the user to restore soft-deleted hostels for a school.'],
    ['name' => 'hostel.force-delete', 'display_name' => 'Permanently Delete Hostels', 'description' => 'Allows the user to permanently delete hostels for a school.'],
    ['name' => 'hostel-room.view-any', 'display_name' => 'View All Hostel Rooms', 'description' => 'Allows the user to view all hostel rooms for a school.'],
    ['name' => 'hostel-room.view', 'display_name' => 'View Hostel Room', 'description' => 'Allows the user to view a specific hostel room for a school.'],
    ['name' => 'hostel-room.create', 'display_name' => 'Create Hostel Rooms', 'description' => 'Allows the user to create new hostel rooms for a school.'],
    ['name' => 'hostel-room.update', 'display_name' => 'Update Hostel Rooms', 'description' => 'Allows the user to update existing hostel rooms for a school.'],
    ['name' => 'hostel-room.delete', 'display_name' => 'Delete Hostel Rooms', 'description' => 'Allows the user to delete hostel rooms for a school.'],
    ['name' => 'hostel-room.restore', 'display_name' => 'Restore Hostel Rooms', 'description' => 'Allows the user to restore soft-deleted hostel rooms for a school.'],
    ['name' => 'hostel-room.force-delete', 'display_name' => 'Permanently Delete Hostel Rooms', 'description' => 'Allows the user to permanently delete hostel rooms for a school.'],
    ['name' => 'hostel-assignment.view-any', 'display_name' => 'View All Hostel Assignments', 'description' => 'Allows the user to view all hostel assignments for a school.'],
    ['name' => 'hostel-assignment.view', 'display_name' => 'View Hostel Assignment', 'description' => 'Allows the user to view a specific hostel assignment for a school.'],
    ['name' => 'hostel-assignment.create', 'display_name' => 'Create Hostel Assignments', 'description' => 'Allows the user to create new hostel assignments for a school.'],
    ['name' => 'hostel-assignment.update', 'display_name' => 'Update Hostel Assignments', 'description' => 'Allows the user to update existing hostel assignments for a school.'],
    ['name' => 'hostel-assignment.delete', 'display_name' => 'Delete Hostel Assignments', 'description' => 'Allows the user to delete hostel assignments for a school.'],
    ['name' => 'hostel-assignment.restore', 'display_name' => 'Restore Hostel Assignments', 'description' => 'Allows the user to restore soft-deleted hostel assignments for a school.'],
    ['name' => 'hostel-assignment.force-delete', 'display_name' => 'Permanently Delete Hostel Assignments', 'description' => 'Allows the user to permanently delete hostel assignments for a school.'],
    ['name' => 'finance-reports.view', 'display_name' => 'View Financial Reports', 'description' => 'View financial reporting dashboard for a school'],
];
