<?php

// Permission catalogue part 1 (Phase 2)
return [
    ['name' => 'dashboard.view', 'display_name' => 'View Dashboard', 'description' => 'Access the main dashboard'],
    ['name' => 'dashboard.edit', 'display_name' => 'Edit Dashboard', 'description' => 'Edit dashboard widgets'],
    ['name' => 'settings.manage', 'display_name' => 'Manage Settings', 'description' => 'Full access to all settings pages'],
    ['name' => 'dynamic-enums.view', 'display_name' => 'View Dynamic Enums', 'description' => 'View Dynamic Enum definitions and effective configuration'],
    ['name' => 'dynamic-enums.manage', 'display_name' => 'Manage Dynamic Enums', 'description' => 'Manage Dynamic Enum configuration in the current authorization context (tenant or school)'],
    ['name' => 'roles.view', 'display_name' => 'View Roles', 'description' => 'View the effective role catalogue for the current authorization context'],
    ['name' => 'roles.manage', 'display_name' => 'Manage Roles', 'description' => 'Create, edit, enable/disable, delete/reset roles and manage role permissions in the current authorization context'],
    ['name' => 'schools.view-any', 'display_name' => 'View All Schools', 'description' => 'Access the list of schools'],
    ['name' => 'schools.view', 'display_name' => 'View School', 'description' => 'Access The detail of individual school'],
    ['name' => 'school.create', 'display_name' => 'Create School', 'description' => 'Create a new school'],
    ['name' => 'school.update', 'display_name' => 'Update School', 'description' => 'Update an existing school'],
    ['name' => 'school.delete', 'display_name' => 'Delete School', 'description' => 'Delete a school'],
    ['name' => 'school.forceDelete', 'display_name' => 'Force Delete School', 'description' => 'Force delete a school'],
    ['name' => 'school.restore', 'display_name' => 'Restore School', 'description' => 'Restore a soft-deleted school'],
    ['name' => 'school-sections.view-any', 'display_name' => 'View All School Sections', 'description' => 'Can see the list of all school sections/divisions in the current school'],
    ['name' => 'school-sections.view', 'display_name' => 'View School Section Details', 'description' => 'Can view detailed information about a specific school section/division'],
    ['name' => 'school-sections.create', 'display_name' => 'Create School Section', 'description' => 'Can add a new school section/division (e.g. Primary, Junior Secondary)'],
    ['name' => 'school-sections.update', 'display_name' => 'Edit School Section', 'description' => 'Can modify existing school sections/divisions'],
    ['name' => 'school-sections.delete', 'display_name' => 'Delete School Section', 'description' => 'Can soft-delete (move to trash) a school section/division'],
    ['name' => 'school-sections.restore', 'display_name' => 'Restore School Section', 'description' => 'Can restore a soft-deleted school section/division from trash'],
    ['name' => 'school-sections.force-delete', 'display_name' => 'Permanently Delete School Section', 'description' => 'Can permanently delete a school section (usually restricted to super-admins)'],
    ['name' => 'user.assign-roles', 'display_name' => 'Assign Roles to User', 'description' => 'Grant or revoke roles and permissions for any user within scope.'],
    ['name' => 'user.change-status', 'display_name' => 'Activate/Deactivate User Account', 'description' => 'Enable or disable a user\'s ability to log in to the system.'],
    ['name' => 'user.reset-password-any', 'display_name' => 'Reset Any User\'s Password', 'description' => 'Force a password reset for any user account.'],
    ['name' => 'user.impersonate', 'display_name' => 'Impersonate User', 'description' => 'Log in as another user for troubleshooting and support purposes. (Highly sensitive)'],
    ['name' => 'user.link-guardian-student', 'display_name' => 'Link Guardian to Student', 'description' => 'Create or manage the official relationship between a Guardian user and one or more Students.'],
    ['name' => 'student.view-any', 'display_name' => 'View All Students', 'description' => 'View list of all students in a school'],
    ['name' => 'student.view', 'display_name' => 'View Student', 'description' => 'View individual student details'],
    ['name' => 'student.create', 'display_name' => 'Create Student', 'description' => 'Create new students'],
    ['name' => 'student.update', 'display_name' => 'Update Student', 'description' => 'Update student information'],
    ['name' => 'student.delete', 'display_name' => 'Delete Student', 'description' => 'Soft delete students'],
    ['name' => 'student.restore', 'display_name' => 'Restore Student', 'description' => 'Restore deleted students'],
    ['name' => 'student.force-delete', 'display_name' => 'Force Delete Student', 'description' => 'Permanently delete students'],
    ['name' => 'staff.view-any', 'display_name' => 'View All Staff', 'description' => 'View all staff in a school'],
    ['name' => 'staff.view', 'display_name' => 'View Staff', 'description' => 'View individual staff details'],
];
