<?php

// Permission catalogue part 3 (Phase 2)
return [
    ['name' => 'class-sections.view', 'display_name' => 'View Class Section', 'description' => 'View detailed information for a specific class section'],
    ['name' => 'class-sections.create', 'display_name' => 'Create Class Section', 'description' => 'Manually create a new class section'],
    ['name' => 'class-sections.update', 'display_name' => 'Update Class Section', 'description' => 'Edit the details of an existing class section'],
    ['name' => 'class-sections.delete', 'display_name' => 'Soft-delete a class section record'],
    ['name' => 'class-sections.restore', 'display_name' => 'Restore Class Section', 'description' => 'Restore a previously trashed class section'],
    ['name' => 'class-sections.force-delete', 'display_name' => 'Force Delete Class Section', 'description' => 'Permanently delete a class section from the database'],
    ['name' => 'class-sections.bulk-generate', 'display_name' => 'Bulk Generate Class Sections', 'description' => 'Generate multiple class arms or sections at once'],
    ['name' => 'class-sections.assign-teacher', 'display_name' => 'Assign Teacher', 'description' => 'Set or change the form teacher for a class section'],
    ['name' => 'class-sections.manage-subjects', 'display_name' => 'Manage Subject Assignments', 'description' => 'Assign or manage subjects for a class section'],
    ['name' => 'class-sections.reorder', 'display_name' => 'Reorder Class Sections', 'description' => 'Change the display sort order of class sections'],
    ['name' => 'class-sections.toggle-status', 'display_name' => 'Toggle Class Status', 'description' => 'Activate or deactivate a class section'],
    ['name' => 'class-levels.view', 'display_name' => 'View Class Levels', 'description' => 'View all class levels within a school section'],
    ['name' => 'class-levels.create', 'display_name' => 'Create Class Levels', 'description' => 'Create new class levels within a school section'],
    ['name' => 'class-levels.update', 'display_name' => 'Update Class Levels', 'description' => 'Edit and update existing class levels'],
    ['name' => 'class-levels.delete', 'display_name' => 'Delete Class Levels', 'description' => 'Soft-delete class levels from a school section'],
    ['name' => 'class-levels.restore', 'display_name' => 'Restore Class Levels', 'description' => 'Restore soft-deleted class levels from trash'],
    ['name' => 'class-levels.force-delete', 'display_name' => 'Permanently Delete Class Levels', 'description' => 'Permanently delete soft-deleted class levels — irreversible'],
    ['name' => 'subjects.view', 'display_name' => 'View Subjects', 'description' => 'View all subjects for a school'],
    ['name' => 'subjects.create', 'display_name' => 'Create Subjects', 'description' => 'Create new subjects for a school'],
    ['name' => 'subjects.update', 'display_name' => 'Update Subjects', 'description' => 'Update existing subjects for a school'],
    ['name' => 'subjects.delete', 'display_name' => 'Delete Subjects', 'description' => 'Delete subjects for a school'],
    ['name' => 'subjects.restore', 'display_name' => 'Restore Subjects', 'description' => 'Restore deleted subjects for a school'],
    ['name' => 'subjects.force-delete', 'display_name' => 'Force Delete Subjects', 'description' => 'Permanently delete subjects for a school'],
    ['name' => 'teacher-assignments.view', 'display_name' => 'View Teacher Assignments', 'description' => 'View all teacher assignments for a school'],
    ['name' => 'teacher-assignments.create', 'display_name' => 'Create Teacher Assignments', 'description' => 'Create new teacher assignments for a school'],
    ['name' => 'teacher-assignments.update', 'display_name' => 'Update Teacher Assignments', 'description' => 'Update existing teacher assignments for a school'],
    ['name' => 'teacher-assignments.delete', 'display_name' => 'Delete Teacher Assignments', 'description' => 'Delete teacher assignments for a school'],
    ['name' => 'teacher-assignments.restore', 'display_name' => 'Restore Teacher Assignments', 'description' => 'Restore deleted teacher assignments for a school'],
    ['name' => 'teacher-assignments.force-delete', 'display_name' => 'Force Delete Teacher Assignments', 'description' => 'Permanently delete teacher assignments for a school'],
    ['name' => 'terms.view', 'display_name' => 'View Terms', 'description' => 'View all terms for a school'],
    ['name' => 'terms.create', 'display_name' => 'Create Terms', 'description' => 'Create new terms for a school'],
    ['name' => 'terms.update', 'display_name' => 'Update Terms', 'description' => 'Update existing terms for a school'],
    ['name' => 'terms.delete', 'display_name' => 'Delete Terms', 'description' => 'Delete terms for a school'],
];
