<?php

namespace Database\Seeders\Settings;

use Illuminate\Database\Seeder;
use RuangDeveloper\LaravelSettings\Facades\Settings;

class SettingsDefaultsSeeder extends Seeder
{
    /**
     * Default values for all settings modules.
     *
     * Run this seeder once (or on fresh installs) to populate global defaults.
     * School-specific overrides will take precedence via getMergedSettings().
     *
     * Note: academic.application defaults are also ensured by ApplicationSettingsDefaultsSeeder.
     */
    public function run(): void
    {
        $defaults = [
            'website.company' => [
                'legal_name' => 'Your School Name',
                'tagline' => 'Excellence in Education',
                'tax_id' => null,
                'public_email' => 'info@yourschool.com',
                'public_phone' => '+234 800 000 0000',
                'website_url' => 'https://yourschool.com',
                'social_facebook' => 'https://facebook.com/yourschool',
                'social_twitter' => 'https://twitter.com/yourschool',
                'social_instagram' => 'https://instagram.com/yourschool',
                'social_linkedin' => null,
                'social_youtube' => 'https://youtube.com/@yourschool',
                'footer_copyright' => '© 2026 Your School Name. All rights reserved.',
                'google_maps_embed' => null,
                'show_address_footer' => true,
                'show_phone_footer' => true,
                'show_email_footer' => true,
            ],
            'website.themes' => [
                'primary_color' => 'indigo',
                'primary_custom_hex' => null,
                'secondary_color' => 'gray',
                'secondary_custom_hex' => null,
                'default_theme' => 'light',
                'dashboard_layout' => 'modern',
                'sidebar_collapsed' => false,
                'menu_position' => 'left',
                'compact_mode' => false,
            ],
            'website.localization' => [
                'timezone' => 'Africa/Lagos',
                'date_format' => 'd/m/Y',
                'time_format' => 'H:i',
                'currency' => 'NGN',
                'currency_position' => 'before',
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'language' => 'en',
                'language_switcher' => true,
                'financial_year' => 2026,
                'allowed_file_types' => ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'webp'],
                'max_file_upload_size' => 5120,
            ],
            'website.social' => [
                'google_enabled' => false,
                'google_client_id' => null,
                'google_client_secret' => null,
                'facebook_enabled' => false,
                'facebook_client_id' => null,
                'facebook_client_secret' => null,
                'microsoft_enabled' => false,
                'microsoft_client_id' => null,
                'microsoft_client_secret' => null,
                'apple_enabled' => false,
                'apple_client_id' => null,
                'apple_team_id' => null,
                'apple_key_id' => null,
                'apple_private_key' => null,
                'twitter_enabled' => false,
                'twitter_client_id' => null,
                'twitter_client_secret' => null,
                'linkedin_enabled' => false,
                'linkedin_client_id' => null,
                'linkedin_client_secret' => null,
            ],
            'website.prefixes' => [
                'student_id' => 'STD',
                'staff_id' => 'STF',
                'parent_id' => 'PAR',
                'invoice' => 'INV',
                'payment' => 'PAY',
                'receipt' => 'REC',
                'class' => 'CLS',
                'section' => 'SEC',
                'subject' => 'SUB',
                'exam' => 'EXM',
                'fee_type' => 'FEE',
                'transport_route' => 'TRT',
                'library_book' => 'LIB',
            ],
            'website.id_formats' => [
                'student_id' => ['pattern' => '{SCHOOL}-{PREFIX}-{YEAR}-{SEQUENCE}', 'sequence_length' => 6],
                'staff_id' => ['pattern' => '{PREFIX}-{SEQUENCE}', 'sequence_length' => 5],
                'guardian_id' => ['pattern' => '{PREFIX}.{SEQUENCE}', 'sequence_length' => 5],
                'invoice' => ['pattern' => 'INV/{YEAR}/{SEQUENCE}', 'sequence_length' => 6],
                'payment' => ['pattern' => 'PAY/{YEAR}/{SEQUENCE}', 'sequence_length' => 6],
                'receipt' => ['pattern' => 'REC/{YEAR}/{SEQUENCE}', 'sequence_length' => 6],
                'class' => ['pattern' => 'CLS-{SEQUENCE}', 'sequence_length' => 3],
                'section' => ['pattern' => 'SEC-{SEQUENCE}', 'sequence_length' => 3],
                'subject' => ['pattern' => 'SUB-{SEQUENCE}', 'sequence_length' => 4],
                'exam' => ['pattern' => 'EXM/{YEAR}/{SEQUENCE}', 'sequence_length' => 4],
                'fee_type' => ['pattern' => 'FEE-{SEQUENCE}', 'sequence_length' => 4],
                'transport_route' => ['pattern' => 'TRT-{SEQUENCE}', 'sequence_length' => 4],
                'library_book' => ['pattern' => 'LIB/{YEAR}/{SEQUENCE}', 'sequence_length' => 5],
            ],
            'general.connected_apps' => [
                'slack' => ['enabled' => false, 'config' => []],
                'google_calendar' => ['enabled' => false, 'config' => []],
                'gmail' => ['enabled' => false, 'config' => []],
                'github' => ['enabled' => false, 'config' => []],
                'zoom' => ['enabled' => false, 'config' => []],
                'whatsapp' => ['enabled' => false, 'config' => []],
            ],
            'general.notifications' => [
                'student_admission' => ['admin' => true, 'parent' => true],
                'admission_enquiry' => ['admin' => true],
                'fee_payment' => ['admin' => true, 'parent' => true],
                'fee_due_reminder' => ['admin' => true, 'parent' => true],
                'fee_overdue' => ['admin' => true, 'parent' => true],
                'attendance_low' => ['admin' => true, 'teacher' => true, 'parent' => true],
                'absent_today' => ['admin' => true, 'teacher' => true, 'parent' => true],
                'exam_result_published' => ['admin' => true, 'teacher' => true, 'parent' => true, 'student' => true],
                'new_assignment' => ['teacher' => true, 'student' => true, 'parent' => true],
                'assignment_due' => ['teacher' => true, 'student' => true, 'parent' => true],
                'event_reminder' => ['admin' => true, 'teacher' => true, 'parent' => true],
                'birthday' => ['admin' => true, 'teacher' => true],
                'system_announcement' => ['admin' => true, 'teacher' => true, 'parent' => true, 'student' => true],
                'leave_approved' => ['admin' => true, 'teacher' => true, 'parent' => true, 'student' => true],
                'leave_requested' => ['admin' => true, 'teacher' => true, 'parent' => true, 'student' => true],
                'leave_rejected' => ['admin' => true, 'teacher' => true, 'parent' => true, 'student' => true],
                'application_submitted' => ['admin' => true, 'parent' => true],
                'application_approved' => ['admin' => true, 'parent' => true],
                'application_rejected' => ['admin' => true, 'parent' => true],
                'admission_offered' => ['admin' => true, 'parent' => true],
                'admission_accepted' => ['admin' => true, 'parent' => true],
                'admission_declined' => ['admin' => true, 'parent' => true],
                'admission_expired' => ['admin' => true, 'parent' => true],
                'admission_deadline_reminder' => ['admin' => true, 'parent' => true],
                'admission_registration_window_reminder' => ['admin' => true, 'parent' => true],
                'enrollment_finalized' => ['admin' => true, 'parent' => true],
                'enrollment_incomplete_reminder' => ['admin' => true, 'parent' => true],
                'enrollment_requirements_reminder' => ['admin' => true, 'parent' => true],
            ],
            'authentication' => [
                'login_throttle_max' => 5,
                'login_throttle_lock' => 15,
                'reset_password_token_life' => 60,
                'allow_password_reset' => true,
                'password_reset_max_attempts' => 5,
                'enable_email_verification' => true,
                'otp_length' => 6,
                'otp_validity' => 10,
                'allow_otp_fallback' => true,
                'allow_user_registration' => true,
                'account_approval' => false,
                'oAuth_registration' => true,
                'show_terms_on_registration' => true,
                'require_password_confirmation' => true,
                'password_confirmation_ttl' => 1800,
                'allow_password_change' => true,
                'password_min_length' => 8,
                'password_require_letters' => true,
                'password_require_mixed_case' => true,
                'password_require_numbers' => true,
                'password_require_symbols' => false,
                'registration_max_attempts' => 5,
                'registration_lock_minutes' => 30,
                'password_update_max_attempts' => 5,
                'password_update_lock_minutes' => 30,
                'otp_verification_max_attempts' => 5,
            ],
            'financial.bank_accounts' => [
                'accounts' => [
                    [
                        'id' => 1,
                        'bank_name' => 'Guaranty Trust Bank',
                        'account_name' => 'Dreams International School - Tuition Account',
                        'account_number' => '0123456789',
                        'branch' => 'Lagos Mainland',
                        'currency' => 'NGN',
                        'notes' => 'For tuition and academic fees only',
                        'is_default' => true,
                    ],
                ],
            ],
            'financial.fees' => [
                'allow_offline_payments' => true,
                'offline_payment_instructions' => "Please transfer fees to any of our bank accounts listed on the invoice.",
                'lock_student_panel_on_default' => false,
                'print_receipt_after_payment' => true,
                'receipt_single_page' => false,
                'late_payment_penalty' => [
                    'enabled' => false,
                    'type' => 'percentage',
                    'amount' => 5.0,
                    'apply_per' => 'once',
                    'grace_period_days' => 7,
                ],
            ],
            'financial.taxes' => [
                'scales' => [
                    ['id' => 1, 'name' => 'VAT', 'rate' => 7.5, 'type' => 'percentage', 'is_default' => true],
                ],
            ],
            'financial.gateways' => [
                'paystack' => ['enabled' => false, 'mode' => 'test', 'credentials' => ['public_key' => '', 'secret_key' => '']],
                'flutterwave' => ['enabled' => false, 'mode' => 'test', 'credentials' => ['public_key' => '', 'secret_key' => '', 'encryption_key' => '']],
                'stripe' => ['enabled' => false, 'mode' => 'test', 'credentials' => ['publishable_key' => '', 'secret_key' => '']],
                'paypal' => ['enabled' => false, 'mode' => 'sandbox', 'credentials' => ['client_id' => '', 'secret' => '']],
            ],
            'academic.attendance_rules' => [
                'minimum_percentage' => 75,
                'count_late_as_half_day' => true,
                'late_grace_minutes' => 15,
                'absent_after_minutes' => 120,
                'notify_parent_at_percentage' => 85,
                'mark_weekends_as_holiday' => true,
                'require_reason_for_absence' => true,
            ],
            'academic.application' => [
                'required' => false,
                'fee_required' => false,
                'fee_amount' => null,
                'fee_type' => 'application_fee',
            ],
            'system.invoice' => [
                'prefix' => 'INV',
                'next_number' => 1,
                'number_digits' => 6,
                'template' => 'modern',
                'due_days' => 14,
                'show_tax' => true,
                'tax_rate' => 7.5,
                'tax_label' => 'VAT',
                'notes' => 'Thank you for your business.',
                'terms' => 'Payment is due within 14 days. Late payments may incur penalties.',
                'show_logo' => true,
            ],
            'system.gdpr' => [
                'content_text' => 'We use cookies to enhance your experience.',
                'position' => 'bottom',
                'show_accept_button' => true,
                'accept_button_text' => 'Accept All',
                'show_decline_button' => true,
                'decline_button_text' => 'Decline',
                'show_link' => true,
                'link_text' => 'Privacy Policy',
                'link_url' => 'https://yourschool.com/privacy-policy',
            ],
            'system.printer' => [
                'paper_width' => 80,
                'margin_top' => 5,
                'margin_bottom' => 5,
                'margin_left' => 3,
                'margin_right' => 3,
                'dpi' => 203,
                'font_size' => 10,
                'show_school_logo' => true,
                'show_receipt_header' => true,
                'header_text' => 'Official Receipt',
                'footer_text' => 'Thank you for your payment',
                'show_barcode' => true,
                'barcode_type' => 'CODE128',
            ],
            'user_management' => [
                'online_admission' => true,
                'online_admission_fee' => 0.00,
                'online_admission_instruction' => 'Complete the form below and submit your application.',
                'allow_student_signin' => true,
                'allow_parent_signin' => true,
                'allow_teacher_signin' => true,
                'allow_staff_signin' => true,
                'enrollment_id_format' => '{prefix}{year}{number}',
                'enrollment_id_number_length' => 6,
                'require_guardian_email' => true,
                'max_guardian_students' => 10,
                'allow_bulk_user_creation' => true,
            ],
            'communication.email' => [
                'driver' => 'smtp',
                'from_name' => 'Your School Name',
                'from_email' => 'no-reply@yourschool.com',
                'reply_to' => null,
                'smtp_host' => '',
                'smtp_port' => 587,
                'smtp_encryption' => 'tls',
                'smtp_username' => '',
                'smtp_password' => '',
                'mailgun_api_key' => '',
                'sendgrid_api_key' => '',
                'postmark_api_key' => '',
                'ses_key' => '',
                'ses_secret' => '',
                'ses_region' => 'us-east-1',
            ],
            'sms' => [
                'enabled' => true,
                'global_sender_id' => 'YourSchool',
                'rate_limit_per_minute' => 60,
                'providers' => [
                    'twilio' => ['enabled' => false, 'priority' => 10, 'sender_id' => null, 'credentials' => ['account_sid' => '', 'auth_token' => '']],
                    'nexmo' => ['enabled' => false, 'priority' => 20, 'sender_id' => null, 'credentials' => ['api_key' => '', 'api_secret' => '']],
                ],
            ],
            'communication.otp' => [
                'delivery_channel' => 'sms',
                'fallback_to_email' => true,
                'sms_template' => 'Your verification code is {code}. Valid for {minutes} minutes.',
                'email_subject' => 'Your Verification Code',
                'email_template' => '<p>Your verification code is <strong>{code}</strong>.</p>',
                'rate_limit_attempts' => 5,
                'rate_limit_minutes' => 15,
            ],
            'others.maintenance' => [
                'mode' => 'disabled',
                'bypass_key' => 'secret-maintenance-key-2026',
                'custom_url' => null,
            ],
            'advanced.storage' => [
                'driver' => 'local',
                'enabled' => true,
                'config' => ['key' => '', 'secret' => '', 'bucket' => '', 'region' => 'us-east-1', 'url' => null],
            ],
        ];

        foreach ($defaults as $key => $value) {
            SaveOrUpdateSchoolSettings($key, $value, null);
        }
    }
}
