<?php

namespace App\Events;

use App\Models\User;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class UserAccountCreated
{
    use Dispatchable, SerializesModels;

    public $user;
    public $plainPassword;
    public $autoGenerated;

    public function __construct(User $user, string $plainPassword, bool $autoGenerated)
    {
        $this->user = $user;
        $this->plainPassword = $plainPassword;
        $this->autoGenerated = $autoGenerated;
    }
}
